(*
 * Client Proxy Procededure Header File for dce
 * for language Delphi, version (3.0)
 * generated by Entera IDL version (1.0)
 * on Fri Sep 04 21:01:47 1998
 *
 * Interface:
 * file name: fractal.idl
 * name: fractal
 * uuid: 61a740ae-9699-11d1-aa8b-00c04fb17a3a version(1.1)
 *
 * Service Interface:
 * file name: fractal.idl
 *)

unit fractal_hc;
interface

uses odenconst40, oden40;


type
hndl_t = Cardinal;
mndset_t = record
	imag_min : double;
	imag_max : double;
	real_min : double;
	real_max : double;
end;

client_data_t = record
	hostname : String;
	infrastructur : String;
	lan : String;
	width : smallint;
	height : smallint;
	iterations : byte;
	mndset : mndset_t;
	rpc_requests : Cardinal;
	bytes_received : Cardinal;
	bytes_sent : Cardinal;
	rpc_time : Cardinal;
end;

server_data_t = record
	hostname : String;
	handles : Word;
	rpc_requests : Cardinal;
	bytes_received : Cardinal;
	bytes_sent : Cardinal;
	rpc_time : Cardinal;
end;

fractal_t_p = ^fractal_t;
fractal_t = record
	handle : Cardinal;
	width : smallint;
	height : smallint;
	iterator : byte;
	x : double;
	y : double;
	r : double;
	i : double;
	d : Longint;
	v : Longint;
	u : Longint;
	a : double;
	mndset : mndset_t;
	xr : double;
	yi : double;
	delta_a : double;
	delta_b : double;
	b : double;
	client_data : client_data_t;
	next : fractal_t_p;
end;

fractal_t = fractal_t;


implementation
end.