/*
 * Server Main Procededure Code for dce
 * for language C, version (1.0)
 * generated by Entera IDL version (1.0)
 * on Fri Sep 04 21:01:47 1998
 *
 * Service Interface: fractal
 *
 * Interfaces:
 *
 *   file name: fractal.idl
 *   name: fractal
 *   uuid: 61a740ae-9699-11d1-aa8b-00c04fb17a3a version(1.1)
 *
 */

#ifndef _MACINTOSH_
#include <stdio.h>
#include <stdlib.h>
#include <dce/idlbase.h>
#include <dce/rpc.h>
#include <dce/nbase.h>
#else
#include "stdio.h"
#include "stdlib.h"
#include "dce/idlbase.h"
#include "dce/rpc.h"
#include "dce/nbase.h"
#endif
#include "ode.h"
#include "odestub.h"


#include "fractal_s.h"

#define CHECK_STATUS(status) \
{ \
	if (status != error_status_ok)\
	{\
		int temp_status;\
		dce_error_string_t error_string;\
		dce_error_inq_text(status, error_string, &temp_status);\
		fprintf (stderr, "Error: %s\n", error_string);\
		return (-1);\
	}\
}

void ode_dstb_register_fractal_1_1 (char* IsDed, error_status_t* odepStatus);

static ode_svr_handle_t server_h;
static char*            parent_args;

int main (int argc, char** argv)
{
	char*            dapfile = NULL;
	char*            password = NULL;
	error_status_t   status;
	error_status_t   local_status;

	/*
	 * Check the command arguments:
	 *       (1) dapfile filename
	 *       (2) new server account password
	 */

	status = ode_stb_parse_command_line (
		argc,
		argv,
		&parent_args,
		&dapfile, 
		&password); 
	CHECK_STATUS(status);

	/*
	 * Setup the server attributes by reading in the
	 * application profile.
	 */
	status = ode_stb_svr_setenv (
		"fractal", dapfile, 1, 1,
		parent_args, argc, argv);
	CHECK_STATUS(status);

	ode_dstb_register_fractal_1_1 (parent_args, &status);
	CHECK_STATUS(status);

	/*
	 * Setup the server process.
	 */
	if (parent_args == NULL)
	{
		status = ode_stb_svr_setup_procs();
		CHECK_STATUS(status);
	}

#	ifdef __OS2__
		signal (SIGINT, SIG_IGN);
		signal (SIGTERM, SIG_IGN);
		signal (SIGABRT, SIG_IGN);
		signal (SIGBREAK, SIG_IGN);
#	endif

	if ((parent_args != NULL) || (!ode_svr_is_dedicated()))
	{
		if (!initialize_fractal (argc, argv))
		{
			fprintf (stderr, "Server Initialization function (initialize_fractal) failed\n");
			return -1;
		}
	}

	if (parent_args != NULL)
	{
		status = ode_stb_svr_dedicated_setup_h (
			parent_args,
			password,
			&server_h);
		CHECK_STATUS(status);
	}
	else
	{
		status = ode_stb_svr_setup_h (
			password,
			&server_h);
		CHECK_STATUS(status);
	}

	status = ode_stb_svr_listen_h (server_h);

	if ((parent_args != NULL) || (!ode_svr_is_dedicated()))
	{
		finalize_fractal ();
	}

	local_status = ode_stb_svr_cleanup_h (&server_h);
	CHECK_STATUS(local_status);

	return status;
}

